version: '3.8'

services:
  db:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    environment:
      TZ: America/Manaus
      MYSQL_ROOT_PASSWORD: vasco
    ports:
      - "3307:3306" 

volumes:
  mysql-data:
